### ISSUE TITLE
UNSAFE_componentWillMount in strict mode is not recommended

### ISSUE THREAD

**Issue by clabe45** [mdjfs/electron-jsx#1]
With an empty app in strict mode, i.e.

```jsx
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
```

```jsx
function App () {
  return (
    <div></div>
  )
}
```

I am receiving the error:
> node_modules/react-dom/cjs/react-dom.development.js:67 Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.
>
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
>
> Please update the following components:
> SideEffect(NullComponent)

---

I believe the fix is to replace your dependency *react-helmet* with *react-helmet-async* (as described [here](https://dev.to/benborgers/how-to-fix-react-helmet-componentwillmount-has-been-renamed-error-ipo)). If you would like I can open a PR for this.

**Comment by mdjfs** [comment]
Hello ! Thanks to be the first person publishing an issue.

Ya for sure, I uses react-helmet when you import any CSS file in a component. I have to see the react-helmet-async to know how i can integrate that in transpiler, thanks for comment that

Also, if you're interested to contribute/help you can contact me using my email (marcos.fuenmayorhtc@gmail.com)

👍👍👍

**Comment by mdjfs** [comment]
Fixed that issue. I not use react-helmet, instead of that. I use JSX components for CSS handling. (Some bugs, but i can fix later, and you will not see the issue if you aren't working with CSS files
